pipeline {
	agent any
	stages {

		stage('Linting HTML file') {
			steps {
				
				sh 'html-minifier-lint Deploy/index.html'
				
				
			}
		}
		
		stage('Linting Dockerfile') {
			steps {
				sh 'cp Deploy/Dockerfile .'
				sh 'dockerlint Dockerfile'
			}
		}
		
		stage('Build Docker Image') {
			steps {
				withDockerRegistry(credentialsId: 'docker', url: 'https://index.docker.io/v1/')  {
					sh '''
						docker build -t shreeni123/shree-capstone .
					'''
				}
			}
		}

		stage('Push Image To Dockerhub') {
			steps {
				withDockerRegistry(credentialsId: 'docker', url: 'https://index.docker.io/v1/')  {
					sh '''
						docker push shreeni123/shree-capstone
					'''
				}
			}
		}

		stage('Deploy Blue Container') {
			steps {
				withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'jenkins', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
					sh '''
						kubectl apply -f Deploy/blue-controller.yaml
					'''
				}
			}
		}

		stage('Deploy Green Container') {
			steps {
				withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'jenkins', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
					sh '''
						kubectl apply -f Deploy/green-controller.yaml
					'''
				}
			}
		}

		stage('Create Service, --> Blue') {
			steps {
				withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'jenkins', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
					sh '''
						kubectl apply -f Deploy/blue-service.yaml
					'''
				}
			}
		}

		stage('User Input') {
            steps {
                input "Ready to redirect traffic to green?"
            }
        }

		stage('CCreate Service, --> Green') {
			steps {
				withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'jenkins', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
					sh '''
						kubectl apply -f Deploy/green-service.yaml
					'''
				}
			}
		}

	}
}
