pipeline {
	agent any
	stages {

		stage('Linting') {
			steps {
				sh 'html-minifier-lint index.html'
			}
		}
		
		stage('Build Docker Image') {
			steps {
				withDockerRegistry(credentialsId: 'docker', url: 'https://index.docker.io/v1/')  {
					sh '''
						docker build -t shreeni123/shree-capstone .
					'''
				}
			}
		}

		stage('Push Image To Dockerhub') {
			steps {
				withDockerRegistry(credentialsId: 'docker', url: 'https://index.docker.io/v1/')  {
					sh '''
						docker push shreeni123/shree-capstone
					'''
				}
			}
		}

		stage('Set Current Kubectl Context') {
			steps {
				withAWS(credentials: 'jenkins', region: 'us-east-2') {
					sh '''
						aws eks update-kubeconfig --name blue-green  --region us-east-2
						kubectl config use-context arn:aws:eks:us-east-2:692963223244:cluster/blue-green
					'''
				}
			}
		}

		stage('Deploy Blue Container') {
			steps {
				withAWS(credentials: 'jenkins', region: 'us-east-2') {
					sh '''
						kubectl apply -f blue-controller.yaml
					'''
				}
			}
		}

		stage('Deploy Green Container') {
			steps {
				withAWS(credentials: 'jenkins', region: 'us-east-2') {
					sh '''
						kubectl apply -f green-controller.yaml
					'''
				}
			}
		}

		stage('Create Service, --> Blue') {
			steps {
				withAWS(credentials: 'jenkins', region: 'us-east-2') {
					sh '''
						kubectl apply -f blue-service.yaml
					'''
				}
			}
		}

		stage('User Input') {
            steps {
                input "Ready to redirect traffic to green?"
            }
        }

		stage('CCreate Service, --> Green') {
			steps {
				withAWS(credentials: 'jenkins', region: 'us-east-2') {
					sh '''
						kubectl apply -f green-service.yaml
					'''
				}
			}
		}

	}
}
